name: render-site

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  render-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          GITHUB_TOKEN: ${{ secrets.PAT_SECRET }}
        run: |
          gh workflow run render-site.yaml -R seabbs/seabbs.github.io
